force-app/main/default/objects/Case/fields/Is_WorkForcePlanner_notified__c.field-meta.xml
<CustomField>
    <fullName>Is_WorkForcePlanner_notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is WorkForcePlanner notified ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/objects/Case/fields/WFM_Service_Invocation_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>WFM_Service_Invocation_Timestamp__c</fullName>
    <label>WFM Service Invocation Timestamp</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Case/fields/Workforce_Planning_Error__c.field-meta.xml
<CustomField>
    <fullName>Workforce_Planning_Error__c</fullName>
    <label>Workforce Planning Error</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkforceManagementServiceTest.cls
@isTest
private class WorkforceManagementServiceTest {
    @TestSetup
    static void createData(){
        insert TestDataFactory.createCases(250);
    }
    @isTest static void positiveTest() {

        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('WFMMockResponseSuccess');
        mock.setStatusCode(200);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);

        List<Case> cases  = new List<Case>();
        for (Case c : [SELECT status FROM Case]) {
            c.Status = 'Closed';
            cases.add(c);
        }
        Test.startTest();
        Update cases;
        Test.stopTest();
        System.assertEquals(50, [SELECT Status, Secret_Key__c, Is_WorkForcePlanner_notified__c FROM Case WHERE Is_WorkForcePlanner_notified__c = true AND WFM_Service_Invocation_Timestamp__c != null].size(), '50 cases are processed successfully');
    }

    @isTest static void negativeTest() {
        StaticResourceCalloutMock mock = new StaticResourceCalloutMock();
        mock.setStaticResource('WFMMockResponseFailure');
        mock.setStatusCode(500);
        mock.setHeader('Content-Type', 'application/json');
        Test.setMock(HttpCalloutMock.class, mock);

        List<Case> cases  = new List<Case>();
        for (Case c : [SELECT status FROM Case]) {
            c.Status = 'Closed';
            cases.add(c);
        }
        Test.startTest();
        Update cases;
        Test.stopTest();
        System.assertEquals(50, [SELECT Status, Secret_Key__c, Is_WorkForcePlanner_notified__c FROM Case WHERE Is_WorkForcePlanner_notified__c = false AND Workforce_Planning_Error__c != null].size(), '50 case records should have an error message');

    }
}