force-app/main/default/objects/Case/fields/Is_WorkForcePlanner_notified__c.field-meta.xml
<CustomField>
    <fullName>Is_WorkForcePlanner_notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is WorkForcePlanner notified ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Case/fields/Secret_Key__c.field-meta.xml
<CustomField>
    <fullName>Secret_Key__c</fullName>
    <label>Secret Key</label>
    <length>100</length>
    <maskChar>asterisk</maskChar>
    <maskType>all</maskType>
    <type>EncryptedText</type>
</CustomField>

force-app/main/default/classes/CaseTriggerHandler.cls
/**
 * @Author             : Vineeth Batreddy
 * @Description        : This class handles all trigger execution logic for Case
**/
public with sharing class CaseTriggerHandler extends TriggerHandler{

    public override void afterUpdate() {

        try {
            List<Id> closedCases = new List<Id>();
            map<Id, Case> before = (Map<Id, Case>)Trigger.oldMap;
            map<Id, Case> after = (Map<Id, Case>)Trigger.newMap;
            List<Id> enqueJobIds = new List<Id>();
            for(Id caseId : after.keySet()){ 
                if (after.get(caseId).Status == GlobalConstants.CASE_STATUS_CLOSED &&
                    before.get(caseId).Status != GlobalConstants.CASE_STATUS_CLOSED &&
                    after.get(caseId).Secret_Key__c == null &&
                    !after.get(caseId).Is_WorkForcePlanner_notified__c) {
                        closedCases.add(caseId);
                }            
            }
            if (!closedCases.isEmpty()) {
                Integer queueableLimit = LIMITS.getLimitQueueableJobs() - LIMITS.getQueueableJobs();
                for (Integer c=0; c < queueableLimit; c++) {
                    Id caseRecordId = closedCases.get(c);
                    System.enqueueJob(new WorkforceManagementQueuable(caseRecordId, after.get(caseRecordId).OwnerId));
                }  
            }          
        } catch (Exception e) {
            insert ExceptionLogUtility.constructException('CaseTriggerHandler', 'ERR-003', e); 
        }
    } 
}