force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCPT-{000000}</displayFormat>
        <label>Exception Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/Integration_Log__c.object-meta.xml
<CustomObject>
    <label>Integration Log</label>
    <nameField>
        <displayFormat>INT-LOG-{000000}</displayFormat>
        <label>Integration Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Integration Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Integration_Log__c/fields/Exception_Details__c.field-meta.xml
<CustomField>
    <fullName>Exception_Details__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Exception Details</label>
    <referenceTo>Exception_Log__c</referenceTo>
    <relationshipLabel>Integration Logs</relationshipLabel>
    <relationshipName>Integration_Logs</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Is_Exception__c.field-meta.xml
<CustomField>
    <fullName>Is_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Request_Response__c.field-meta.xml
<CustomField>
    <fullName>Request_Response__c</fullName>
    <label>Request / Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/sObjectId__c.field-meta.xml
<CustomField>
    <fullName>sObjectId__c</fullName>
    <label>sObjectId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Integration_Log__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>Indicates whether this record is for request or a response</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Request</fullName>
            </value>
            <value>
                <fullName>Response</fullName>
            </value>
            <value>
                <fullName>Acknowledgement</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/IntegrationLogUtility.cls
public without sharing class IntegrationLogUtility {

    public static Integration_Log__c constructIntegrationLog(String serviceName, String sObjectId, String type, String payload, Boolean isException, Id exceptionLogRecord) {
        Integration_Log__c integrationLog = new Integration_Log__c();
        integrationLog.Service_Name__c = serviceName;
        integrationLog.sObjectId__c = sObjectId;
        integrationLog.Timestamp__c = System.now();
        integrationLog.Type__c = type;
        integrationLog.Request_Response__c = payload;
        if(isException!=null)
            integrationLog.Is_Exception__c = isException;
        if(exceptionLogRecord!=null)
            integrationLog.Exception_Details__c = exceptionLogRecord;

        return integrationLog;
    }

    public static void commitIntegrationLogs(List<Integration_Log__c> integrationLogs) {
        if(integrationLogs!=null && integrationLogs.size()>0)
            upsert integrationLogs;
    }

    public static List<Integration_Log__c> addException(List<Integration_Log__c> integrationLogs, Exception_Log__c exceptionLog) {
        if(integrationLogs.size()>0 && exceptionLog!=null) {
            for(Integration_Log__c integrationLog : integrationLogs) {
                integrationLog.Exception_Details__c = exceptionLog.Id;
                integrationLog.Is_Exception__c = true;
            }
        }

        return integrationLogs;
    }
}