force-app/main/default/objects/Exception_Log__c/Exception_Log__c.object-meta.xml
<CustomObject>
    <label>Exception Log</label>
    <nameField>
        <displayFormat>EXCPT-{000000}</displayFormat>
        <label>Exception Log</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Exception Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Exception_Log__c/fields/Business_Function_Name__c.field-meta.xml
<CustomField>
    <fullName>Business_Function_Name__c</fullName>
    <label>Business Function Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Is_Admin_Notified__c.field-meta.xml
<CustomField>
    <fullName>Is_Admin_Notified__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Admin Notified ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Is_Case_Created__c.field-meta.xml
<CustomField>
    <fullName>Is_Case_Created__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Case Created ?</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Is_Integration_Exception__c.field-meta.xml
<CustomField>
    <fullName>Is_Integration_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Is Integration Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Logged_in_User__c.field-meta.xml
<CustomField>
    <fullName>Logged_in_User__c</fullName>
    <label>Logged in User</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Exception_Log__c/fields/Stack_Trace__c.field-meta.xml
<CustomField>
    <fullName>Stack_Trace__c</fullName>
    <label>Stack Trace</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/classes/ExceptionLogUtility.cls
public without sharing class ExceptionLogUtility {
    
    private static final String NO_RESPONSE = 'No response from the API';

    public static Exception_Log__c constructException(String businessFunctionName, String errorCode, Exception ex) {
        Exception_Log__c excpLog = new Exception_Log__c();
        excpLog.Business_Function_Name__c = businessFunctionName;
        excpLog.Error_Code__c = errorCode;
        excpLog.Error_Message__c = ex.getMessage();
        excpLog.Is_Admin_Notified__c = false;
        excpLog.Is_Case_Created__c = false;
        excpLog.Is_Integration_Exception__c = false;
        excpLog.Logged_in_User__c = UserInfo.getName();
        excpLog.Stack_Trace__c = ex.getStackTraceString();
        excpLog.Timestamp__c = System.now();

        return excpLog;
    }

    public static void commitExceptions(List<Exception_Log__c> exceptions) {
        if(exceptions!=null && exceptions.size()>0)
            upsert exceptions;
    }

    public static Exception_Log__c noResponseException(String businessFunction, String errorCode) {
        return constructException(businessFunction, errorCode, null);
    }
}