force-app/main/default/objects/Mock_Configuration__mdt/Mock_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>This custom metadata configuration holds all the settings to enable/disable mock services during runtime. Enabling mocks here will route all API traffic to mock server</description>
    <label>Mock Configuration</label>
    <pluralLabel>Mock Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/Mock_Configuration__mdt/fields/Mock_Url__c.field-meta.xml
<CustomField>
    <fullName>Mock_Url__c</fullName>
    <label>Mock Url</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/MockUtility.cls
/**
 * @Author             : Vineeth Batreddy
 * @Description        : This class holds all utility methods for mock configuration
**/
public without sharing class MockUtility {

    public static Map<String, String> getMock(String name) {

        Map<String,String> filters = new Map<String, String>();
        filters.put('MasterLabel', name);
        Mock_Configuration__mdt mock = (Mock_Configuration__mdt) QueryUtils.getRecord('Mock_Configuration__mdt', filters, null);
        System.debug('!@#$% mock : ' + mock);

        Map<String,String> mockConfig = new Map<String, String>();
        if(mock != null) {
            mockConfig.put('name', mock.MasterLabel);
            mockConfig.put('url', mock.Mock_Url__c);
            mockConfig.put('isEnabled', String.valueOf(mock.Enable__c));	
        }

        return mockConfig;
    }

    public static Boolean isEnabled(String name) {
        Map<String, String> mockConfig = getMock(name);
        if(mockConfig.size()>0 && mockConfig.get('isEnabled').equalsIgnoreCase('true'))
            return true;
        else
            return false;
    }

    public static String getMockEndpoint(String name) {
        Map<String, String> mockConfig = getMock(name);
        if(mockConfig.size()>0 && mockConfig.get('isEnabled').equalsIgnoreCase('true'))
            return mockConfig.get('url');
        else
            return '';
    }
}